
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { useEffect } from "react";
import { preventCloseOnScroll } from "./utils/preventCloseOnScroll";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // useEffect(() => {
  //   preventCloseOnScroll();
  // }, []);
  return (
    <html lang="en">
      <head>
        {/* Add Telegram SDK script */}
        <script async src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
